// Code generated by Prismic. DO NOT EDIT.

import About from "./About";
import Hero from "./Hero";
import Works from "./Works";

export const components = {
	about: About,
	hero: Hero,
	works: Works
};